// This file was automatically generated by the Soy compiler.
// Please don't edit this file by hand.
// source: templates/home.soy

/**
 * @fileoverview Templates in namespace example.templates.
 * @public
 */

goog.provide('example.templates');

goog.requireType('goog.soy');
goog.require('soy');
goog.require('soy.asserts');
goog.require('soydata.VERY_UNSAFE');


/**
 * @param {example.templates.welcome.Params} opt_data
 * @param {(?goog.soy.IjData|?Object<string, *>)=} opt_ijData
 * @param {(?goog.soy.IjData|?Object<string, *>)=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
example.templates.welcome = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!goog.soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  /** @type {string} */
  var greeting = soy.asserts.assertType(typeof opt_data.greeting === 'string', 'greeting', opt_data.greeting, 'string');
  /** @type {number} */
  var year = soy.asserts.assertType(typeof opt_data.year === 'number', 'year', opt_data.year, 'number');
  return soydata.VERY_UNSAFE.ordainSanitizedHtml('<h1 id="greeting"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="example.templates.welcome templates/home.soy:5"' : '') + '>' + soy.$$escapeHtml(greeting) + '</h1>The year is ' + soy.$$escapeHtml(year) + '.');
};
/**
 * @typedef {{
 *  greeting: string,
 *  year: number,
 * }}
 */
example.templates.welcome.Params;
if (goog.DEBUG) {
  example.templates.welcome.soyTemplateName = 'example.templates.welcome';
}
